### ISSUE TITLE
야마 DrawService 종료시 LockScreenActivity 살아있습니다.

### ISSUE THREAD

**Issue by yamamamo** [johits/smart_wb#12]
메인 타이머 시작 -> 락스크린 드로서비스 시작 -> 드로서비스 종료 -> 메인으로 화면 전환
->메인에서 백버튼 터치 -> 락스크린액티비티로 전환. 

드로서비스 종료시 락스크린 액티비티도 파괴해야 합니다.

우선 개발하던 것 개발하고 추후 처리하겠습니다.

**Comment by johits** [comment]
수정 후 main으로 push
