### ISSUE TITLE
스크린 타임 종료 버튼 글씨 크기 변동

### ISSUE THREAD

**Issue by yamamamo** [johits/smart_wb#21]
![이슈3](https://user-images.githubusercontent.com/84963245/122661003-03f1be80-d1c1-11eb-8946-875b36c467c4.png)

**Comment by johits** [comment]
해당 이슈 수정 완료. 수정된 코드는 차트 코드 수정 후 같이 올릴 예정. 메인에 올리기 전 채팅 드리겠습니다.
