### ISSUE TITLE
타이머 다이얼로그 수정 요청

### ISSUE THREAD

**Issue by johits** [johits/smart_wb#22]
![요청2](https://user-images.githubusercontent.com/74091087/122664414-3230c780-d1dc-11eb-8392-95c34ddc9ebd.jpg)
![요청1](https://user-images.githubusercontent.com/74091087/122664415-3361f480-d1dc-11eb-8609-6f30877b730d.jpg)

**Comment by yamamamo** [comment]
수정했읍니다.
