### ISSUE TITLE
캘린더 초기 세팅 문제 수정 요청

### ISSUE THREAD

**Issue by johits** [johits/smart_wb#25]
![달력요청](https://user-images.githubusercontent.com/74091087/122664881-f814f500-d1de-11eb-8bd9-c6669d302af4.jpg)
다른 일자에 있다가 상단 가운데 '6월 2021'이라는 부분 클릭 시에도 월 전체 달력 이미지로 들어가지나 상세보기가 세팅이 안 됩니다. 날짜도 2021 6월로 연도 다음 월이 나올 수 있도록 수정 요청합니다

**Comment by yamamamo** [comment]
수정완료
