### ISSUE TITLE
타이머 시간 흐름 오류 발견

### ISSUE THREAD

**Issue by johits** [johits/smart_wb#26]
오후 7시쯤 타이머 10시간 설정 맞춰놓음. 오전 9시 58분에 촬영한 타이머 사진. 타이머 시간 5시간 48분 남아있음
![KakaoTalk_20210621_095835110](https://user-images.githubusercontent.com/74091087/122694112-4fff3a80-d277-11eb-9770-151e7d614547.jpg)

**Comment by yamamamo** [comment]
기능 수정 완료
