### ISSUE TITLE
타이머 2중 작동 수정 요청

### ISSUE THREAD

**Issue by johits** [johits/smart_wb#28]
타이머 작동중에 휴대폰 재부팅할 경우
기존 타이머 세팅 되는 동안 스마트 웰빙 앱 들어가서 타이머 세팅 한 번 더 하면 2중으로 타이머가 작동됨
타이머 2개 중 타이머 하나가 종료되면 나머지 하나는 흰 액티비티만 떠 있는 상태로 꺼지지 않는 벽돌 상태가 됨
(쉐어드 이용해서 이미 작동중인 타이머가 있다면 시간 설정 못 하게 막아야 함)

**Comment by yamamamo** [comment]
수정 완료
