### ISSUE TITLE
타이머 종료 다이얼로그 UI 수정 요청

### ISSUE THREAD

**Issue by johits** [johits/smart_wb#29]
![image](https://user-images.githubusercontent.com/74091087/123190739-17f83180-d4db-11eb-93b8-484b7ac1cb38.png)

다시 시도해주세요 -> 종료되었습니다
성공할 경우 -> 목표 시간 성공! (더 좋은 문구가 있다면 의견 바랍니다)
설정시간 -> 설정 시간
획득한꽃 -> 획득한 꽃
부재중전화 -> 부재중 전화

획득한 꽃 '송이'라는 단위 붙여주기

획득한 꽃 없을 경우 X -> 0 송이
부재중 전화 없을 경우 X-> 없음

**Comment by johits** [comment]
UI 수문구 변경 및 확인 버튼 여백 줘서 main2에 올렸습니다
밑에 문구가 상단 타이틀 문구와 정가운데 일치시키는 디테일은 시간 남으면 마저 작업하겠습니다
----------------------------- 
 설정 시간       00분
 획득한 꽃      0송이
 부재중 전화   없음
------------------------------

**Comment by yamamamo** [comment]
확인했읍니다.
