### ISSUE TITLE
달력 UI 수정 요청

### ISSUE THREAD

**Issue by johits** [johits/smart_wb#30]
![image](https://user-images.githubusercontent.com/74091087/123191172-cd2ae980-d4db-11eb-8d52-b48e314320a0.png)

상세 보기 명칭 변경
도전시간 합 -> 총 도전 시간
성공시간 합 -> 총 성공 시간
획득한꽃 합 -> 총 획득한 꽃

시간 표기
05시간 00분  -> 5시간
00시간 27분 -> 27분
획득한 꽃 -> 0송이 ('송이' 단위 붙여줄 것)
----------------------------------------------------------------------------------------------------------------------------------------
기록 있을 경우 빨간 점 - >메인 블루 컬러로 변경
오늘 날짜 표시하고 있는 네모칸 없애고 회색 동그라미로 표시 후 다른 날짜 클릭시 회색 동그라미가 이동하게끔 수정 요청
----------------------------------------------------------------------------------------------------------------------------------------
상단 날짜 6월 2021년
2021년 6월로 수정 요청

**Comment by yamamamo** [comment]
상세보기 버튼 크기 수정 필요

**Comment by yamamamo** [comment]
오늘날짜 체크 해제 했읍니다.
