### ISSUE TITLE
스크린타임 동작중 물리버튼 문제

### ISSUE THREAD

**Issue by yamamamo** [johits/smart_wb#33]
스크린타임 종료 후
백버튼 -> 강제종료(액티비티 다이얼로그 문제)
홈버튼 -> 홈화면
목록 -> 목록 보여짐

**Comment by johits** [comment]
back 버튼 제어하고 홈버튼 누를 경우 앱 재실행되게 수정하여 main2에 올림
테스트 해보시고 이상 없으시면 close 바랍니다

**Comment by yamamamo** [comment]
백버튼 메뉴 버튼 작동 이상없읍니다.

**Comment by yamamamo** [comment]
1.스크린타임중 홈버튼누름 -> 몇 초 후 액티비티 생성 -> 이상없이 종료
2.스크린타임 몇 초 안 남았을 때 홈버튼 누름 -> 서비스종료 -> 홈화면(약 3~5초)
  -> 액티비티 생성 -> 결과 다이얼로그 이상 없음
3.스크린타임중 홈버튼 누름 -> 액티비티 생성 전 홈 버튼 누름 -> 액티비티 생성 x -> 종료되면 핸드폰홈화면

3번의 경우 액티비티 생성 전 홈 버튼 누르는 것은 앱에서 동작 하는 것이 아닌 핸드폰 홈화면에서 동작. 
 그래서 액티비티가 생성 안 되는 것으로 보인다.
