### ISSUE TITLE
타이머 종료 후 에러 발생

### ISSUE THREAD

**Issue by johits** [johits/smart_wb#34]
![image](https://user-images.githubusercontent.com/74091087/123192700-678c2c80-d4de-11eb-9c95-e9cdae9149de.png)

에러 내용:    android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@f75a4e9 is not valid; is your activity running?

액티비티 흰화면 상태에서 종료 다이얼로그가 뜨지 않고 알림소리만 연달아 4,5번 정도 울림

**Comment by yamamamo** [comment]
다이얼로그 ->메인에서 생성되는 것으로 수정
