### ISSUE TITLE
아이템 기능 수정 요청

### ISSUE THREAD

**Issue by johits** [johits/smart_wb#35]
![image](https://user-images.githubusercontent.com/74091087/123192855-af12b880-d4de-11eb-9a1e-c50b9bd28a4d.png)
아이템 구매하였으나 메인 타이머 갔다가 다시 아이템 메뉴로 오게 되면 모든 아이템에 자물쇠가 걸려 있음

**Comment by yamamamo** [comment]
동일 증상 확인 했읍니다.

0원일 때 구입 안됨 .꽃송이 부족하다 다이얼로그 확인
	미리보기 테스트 이상 없음
	구입하면 바로 화면 적용 되는 것 확인 
	다른 화면 다녀오면 구매 버튼 -> 잠금버튼으로 변경 된다 -> 아이템 구매할 수 있다.
	새로고침 동작 x

**Comment by johits** [comment]
수정 완료
