### ISSUE TITLE
타이머 종료 알림 수정 요청

### ISSUE THREAD

**Issue by johits** [johits/smart_wb#36]
1회 알림 -> 사용자가 종료 다이얼로그에서 확인 버튼 누르면 알림 꺼지게 수정 요청

**Comment by johits** [comment]
기존 - > 상단 노티피 알림과 함께 알림 1회만 뜸
수정 후 -> 상단 노티피와 별도로 다이얼로그 뜰 때 알림이 울리고 확인 버튼을 눌러야 알림 꺼짐으로 수정하였습니다
main2에는 종료 다이얼로그 문구 변경과 수정해서 함께 올리겠습니다

테스트 해보시고 이상 없다면 close 바랍니다

**Comment by yamamamo** [comment]
노티피케이션 사용 x

다이얼로그 생성시 알람, 진동, 무음 동작 이상 없읍니다.
